version: "3.7"
services:
  sciparo:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mongo_db:
        condition: service_healthy
    env_file:
      - .env

  mongo_db:
    image: "mongo:5.0.2"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s
