spring:
  config:
    import: optional:file:.env[.properties]
  security:
    filter:
      order: 10
    oauth2:
      client:
        registration:
          github:
            client-id: f7db273e620fc3fa4cd8
            client-secret: e66cd833db1bfe0ae726b110e5ff2bdeb2cc6b98
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RPS_DB

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

server:
  address: 0.0.0.0

frontend:
  url: http://localhost:3000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: TRACE
        security: DEBUG
